### ISSUE TITLE
Specifying ansible version

### ISSUE THREAD

**Issue by farridav** [William-Yeh/docker-ansible#9] opened 2015-12-21 13:17 UTC
I've found that using these images massively speeds up my build times, thanks for your work :) 

The only trouble is I need to test against specific versions of ansible.. but the way you build ansible (clone, build, move relevant files and remove cruft) wont allow me to change the ansible version.. 

Had you thought about install from pip so that the version can be changed? or leaving the git repo intact so users can checkout the relevant tag?

Thanks again!

**Comment by William-Yeh** [comment] 2015-12-21 14:38
Hi farridav,

Thanks for this suggestion. I'm always glad to add versioning to these images. The only problem is: How do I assign proper tags to these Docker images?

Do you have any suggestion?

**Comment by farridav** [comment] 2015-12-22 09:45
I hadn't really thought about versioning the images, I was more thinking that if you changed your base images to install the latest ansible via pip, and leave python-pip installed on the box, then users that want a different version could `RUN pip install ansible==<version>` within their own Dockerfiles, not sure if that fits within the idea you had for these images, but worth a thought :)

**Comment by William-Yeh** [comment] 2015-12-22 10:08
Is the following approach okay?

```
# Dockerfile of base image


# the following variable is to be defined in derived images:
# ENV  ANSIBLE_VERSION  1.9.4

#...
ONBUILD  RUN  pip install ansible==$ANSIBLE_VERSION
```

**Comment by farridav** [comment] 2015-12-22 10:20
seems like a good approach, but would you default it to latest? so that specifying ansible version is optional ? you would also need to ensure you install `python-pip`

**Comment by William-Yeh** [comment] 2015-12-22 10:26
I'll add another suite of images (`williamyeh/ansible:ver-ubuntu14.04`, perhaps).  I'm still thinking of proper naming.

**Comment by farridav** [comment] 2015-12-22 10:28
Cool, ill keep an eye on this :) thanks

**Comment by tleyden** [comment] 2016-02-16 23:23
I need to run ansible 2.0 -- what's the best way to do that currently? 

I tried doing a `docker pull williamyeh/ansible:centos7` and `docker run -it williamyeh/ansible:centos7 ansible --version` and it's returning:

> ansible 1.9.4
>   configured module search path = None

**Comment by William-Yeh** [comment] 2016-02-17 02:36
Currently, use the following tags for CentOS images:
- `williamyeh/ansible:master-centos7`
- `williamyeh/ansible:master-centos7-onbuild`
- `williamyeh/ansible:master-centos6`
- `williamyeh/ansible:master-centos6-onbuild`

**Comment by sebas5384** [comment] 2016-03-07 22:26
Hi I need to run Ansible 1.9.x because there are some perfomance regressions https://github.com/ansible/ansible/issues/12239 in the 2.x version.

@William-Yeh specifying `ENV  ANSIBLE_VERSION  1.9.4` should do the trick!
**EDIT:**
... to build the image.

But in order to using it as a base image, I think the best here is to create an tagged image like:

```
williamyeh/ansible:1.9.4-ubuntu14.04
```

from a perfomance point of view is better to have an already builded image with the version.

**Comment by sebas5384** [comment] 2016-03-08 01:03
For the ones that need to downgrade, here's a simpler way of resolving the need of having the older version available:
https://github.com/William-Yeh/docker-ansible/compare/master...TallerWebSolutions:older-version-1.9

And you can use the image with Ansible 1.9:
https://hub.docker.com/r/taller/ansible/

Put in your Dockerfile:

```
FROM taller/ansible:1.9-ubuntu14.04-onbuild
...
```

Hope this helps for now :)

**Comment by William-Yeh** [comment] 2016-03-08 01:53
@sebas5384 Fantastic idea! I'll do it later.

**Comment by William-Yeh** [comment] 2016-03-08 06:25
New images for Ansible 1.9.4 in https://github.com/William-Yeh/docker-ansible/commit/14e54a03841a837231975247f70f063527a6f7b6

Normal series:
- williamyeh/ansible:1.9-debian8
- williamyeh/ansible:1.9-debian7
- williamyeh/ansible:1.9-ubuntu14.04
- williamyeh/ansible:1.9-ubuntu12.04
- williamyeh/ansible:1.9-centos7
- williamyeh/ansible:1.9-centos6
- williamyeh/ansible:1.9-alpine3

Onbuild series:
- williamyeh/ansible:1.9-debian8-onbuild
- williamyeh/ansible:1.9-debian7-onbuild
- williamyeh/ansible:1.9-ubuntu14.04-onbuild
- williamyeh/ansible:1.9-ubuntu12.04-onbuild
- williamyeh/ansible:1.9-centos7-onbuild
- williamyeh/ansible:1.9-centos6-onbuild
- williamyeh/ansible:1.9-alpine3-onbuild

**Closed as completed by William-Yeh** 2016-03-08 06:25 UTC
Labels: enhancement

**Comment by sebas5384** [comment] 2016-03-08 14:18
@William-Yeh great!! :+1:

**Comment by sebas5384** [comment] 2016-03-08 15:15
@William-Yeh did you map the builds with those tags at docker hub?

**Comment by William-Yeh** [comment] 2016-03-09 03:00
@sebas5384 I didn't know that I needed to press the **Trigger** button manually on Docker Hub.

These images should work now.
